package dev.ujhhgtg.wekit.features

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.KSValueParameter
import com.google.devtools.ksp.symbol.Modifier
import com.google.devtools.ksp.symbol.Nullability
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.writeTo

private const val AGENT_TOOL_ANNOTATION = "dev.ujhhgtg.wekit.features.core.AgentTool"
private const val AGENT_TOOL_PARAM_ANNOTATION = "dev.ujhhgtg.wekit.features.core.AgentToolParam"
private const val TOOL_PACKAGE = "dev.ujhhgtg.wekit.agent.tool"
private const val GENERATED_OBJECT = "AgentToolsProvider"

class AgentToolKspProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        AgentToolScanner(environment.codeGenerator, environment.logger)
}

/**
 * Scans every function annotated with [dev.ujhhgtg.wekit.features.core.AgentTool] and generates
 * `dev.ujhhgtg.wekit.agent.tool.AgentToolsProvider.ALL_TOOLS`, a `List<AgentToolDescriptor>`
 * carrying each tool's name, description, side-effect flag, parameter specs (with JSON-schema
 * types derived from the Kotlin parameter types) and a suspend invoker that unpacks the arg map
 * and calls the annotated function directly.
 */
class AgentToolScanner(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    private var generated = false

    private val descriptorClass = ClassName(TOOL_PACKAGE, "AgentToolDescriptor")
    private val paramSpecClass = ClassName(TOOL_PACKAGE, "AgentToolParamSpec")
    private val argsClass = ClassName(TOOL_PACKAGE, "AgentToolArgs")

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (generated) return emptyList()
        generated = true

        val functions = resolver
            .getSymbolsWithAnnotation(AGENT_TOOL_ANNOTATION)
            .filterIsInstance<KSFunctionDeclaration>()
            .toList()

        if (functions.isEmpty()) return emptyList()

        functions.forEach(::validate)

        // Deterministic order: by tool name.
        val sorted = functions.sortedBy { toolName(it) }

        val listType = ClassName("kotlin.collections", "List").parameterizedBy(descriptorClass)

        val initializer = CodeBlock.builder().apply {
            add("listOf(⇥\n")
            sorted.forEachIndexed { index, fn ->
                add(buildDescriptor(fn))
                add(if (index == sorted.lastIndex) "\n" else ",\n")
            }
            add("⇤)")
        }.build()

        val property = PropertySpec.builder("ALL_TOOLS", listType)
            .initializer(initializer)
            .build()

        val objectSpec = TypeSpec.objectBuilder(GENERATED_OBJECT)
            .addKdoc(
                "Auto-generated by [dev.ujhhgtg.wekit.features.AgentToolScanner]. Do not edit manually.\n" +
                        "Registry of every function annotated with [dev.ujhhgtg.wekit.features.core.AgentTool].\n"
            )
            .addProperty(property)
            .build()

        val dependencies = Dependencies(
            aggregating = true,
            *functions.mapNotNull { it.containingFile }.toTypedArray()
        )

        FileSpec.builder(TOOL_PACKAGE, GENERATED_OBJECT)
            .addType(objectSpec)
            .build()
            .writeTo(codeGenerator, dependencies)

        return emptyList()
    }

    private fun validate(fn: KSFunctionDeclaration) {
        val parent = fn.parentDeclaration
        if (parent != null && (parent !is com.google.devtools.ksp.symbol.KSClassDeclaration || parent.classKind != ClassKind.OBJECT)) {
            logger.error(
                "@AgentTool function ${fn.qualifiedName?.asString()} must be top-level or a member of an `object`.",
                fn
            )
        }
        fn.parameters.forEach { p ->
            if (jsonTypeOrNull(p) == null) {
                logger.error(
                    "@AgentTool ${fn.simpleName.asString()} parameter '${p.name?.asString()}' has unsupported type. " +
                            "Allowed: String, Int, Long, Double, Boolean, List<String> (each optionally nullable).",
                    p
                )
            }
        }
    }

    private fun buildDescriptor(fn: KSFunctionDeclaration): CodeBlock {
        val name = toolName(fn)
        val description = annotationString(fn, "description") ?: ""
        val sideEffect = annotationBool(fn, "sideEffect") ?: true
        val group = annotationString(fn, "group") ?: "builtin-wechat"

        val params = CodeBlock.builder().apply {
            if (fn.parameters.isEmpty()) {
                add("emptyList()")
            } else {
                add("listOf(⇥\n")
                fn.parameters.forEachIndexed { index, p ->
                    add(buildParamSpec(p))
                    add(if (index == fn.parameters.lastIndex) "\n" else ",\n")
                }
                add("⇤)")
            }
        }.build()

        val invoker = buildInvoker(fn)

        return CodeBlock.builder()
            .add("%T(⇥\n", descriptorClass)
            .add("name·=·%S,\n", name)
            .add("description·=·%S,\n", description)
            .add("sideEffect·=·%L,\n", sideEffect)
            .add("group·=·%S,\n", group)
            .add("params·=·%L,\n", params)
            .add("invoker·=·%L\n", invoker)
            .add("⇤)")
            .build()
    }

    private fun buildParamSpec(p: KSValueParameter): CodeBlock {
        val (jsonType, itemType) = jsonTypeOrNull(p)!!
        val paramName = p.name!!.asString()
        val required = p.type.resolve().nullability != Nullability.NULLABLE
        val description = paramAnnotationString(p) ?: paramName
        return CodeBlock.builder()
            .add("%T(", paramSpecClass)
            .add("name·=·%S, ", paramName)
            .add("jsonType·=·%S, ", jsonType)
            .apply { if (itemType != null) add("itemType·=·%S, ", itemType) }
            .add("description·=·%S, ", description)
            .add("required·=·%L", required)
            .add(")")
            .build()
    }

    private fun buildInvoker(fn: KSFunctionDeclaration): CodeBlock {
        val call = CodeBlock.builder()
        val owner = fn.parentDeclaration
        if (owner is com.google.devtools.ksp.symbol.KSClassDeclaration) {
            call.add("%T.%N(", owner.toClassName(), fn.simpleName.asString())
        } else {
            val pkg = fn.packageName.asString()
            call.add("%M(", MemberName(pkg, fn.simpleName.asString()))
        }
        if (fn.parameters.isNotEmpty()) {
            call.add("⇥\n")
            fn.parameters.forEachIndexed { index, p ->
                call.add("%L·=·%L", p.name!!.asString(), argAccessor(p))
                call.add(if (index == fn.parameters.lastIndex) "\n" else ",\n")
            }
            call.add("⇤")
        }
        call.add(")")

        // invoker: suspend (AgentToolArgs) -> String
        return CodeBlock.builder()
            .add("{ args:·%T ->⇥\n", argsClass)
            .add("%L\n", call.build())
            .add("⇤}")
            .build()
    }

    private fun argAccessor(p: KSValueParameter): CodeBlock {
        val nullable = p.type.resolve().nullability == Nullability.NULLABLE
        val (jsonType, itemType) = jsonTypeOrNull(p)!!
        val name = p.name!!.asString()
        val method = when {
            jsonType == "array" || itemType != null -> if (nullable) "stringListOrNull" else "stringList"
            jsonType == "string" -> if (nullable) "stringOrNull" else "string"
            jsonType == "boolean" -> if (nullable) "boolOrNull" else "bool"
            jsonType == "number" -> if (nullable) "doubleOrNull" else "double"
            else -> {
                // integer -> Int or Long depending on Kotlin type
                val decl = p.type.resolve().declaration.qualifiedName?.asString()
                if (decl == "kotlin.Long") if (nullable) "longOrNull" else "long"
                else if (nullable) "intOrNull" else "int"
            }
        }
        return CodeBlock.of("args.%L(%S)", method, name)
    }

    /** Returns (jsonType, itemType?) or null if the parameter type is unsupported. */
    private fun jsonTypeOrNull(p: KSValueParameter): Pair<String, String?>? {
        val type = p.type.resolve()
        val qn = type.declaration.qualifiedName?.asString()
        return when (qn) {
            "kotlin.String" -> "string" to null
            "kotlin.Int", "kotlin.Long" -> "integer" to null
            "kotlin.Double", "kotlin.Float" -> "number" to null
            "kotlin.Boolean" -> "boolean" to null
            "kotlin.collections.List" -> {
                val arg = type.arguments.firstOrNull()?.type?.resolve()
                val argQn = arg?.declaration?.qualifiedName?.asString()
                if (argQn == "kotlin.String") "array" to "string" else null
            }
            else -> null
        }
    }

    private fun toolName(fn: KSFunctionDeclaration): String =
        annotationString(fn, "name") ?: fn.simpleName.asString()

    private fun annotationString(fn: KSFunctionDeclaration, arg: String): String? {
        val ann = fn.annotations.firstOrNull {
            it.annotationType.resolve().declaration.qualifiedName?.asString() == AGENT_TOOL_ANNOTATION
        } ?: return null
        return ann.arguments.find { it.name?.asString() == arg }?.value as? String
    }

    private fun annotationBool(fn: KSFunctionDeclaration, arg: String): Boolean? {
        val ann = fn.annotations.firstOrNull {
            it.annotationType.resolve().declaration.qualifiedName?.asString() == AGENT_TOOL_ANNOTATION
        } ?: return null
        return ann.arguments.find { it.name?.asString() == arg }?.value as? Boolean
    }

    private fun paramAnnotationString(p: KSValueParameter): String? {
        val ann = p.annotations.firstOrNull {
            it.annotationType.resolve().declaration.qualifiedName?.asString() == AGENT_TOOL_PARAM_ANNOTATION
        } ?: return null
        return ann.arguments.find { it.name?.asString() == "description" }?.value as? String
    }
}
