package dev.ujhhgtg.wekit.agent.tool

import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.booleanOrNull
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.doubleOrNull
import kotlinx.serialization.json.intOrNull
import kotlinx.serialization.json.jsonPrimitive
import kotlinx.serialization.json.longOrNull
import kotlinx.serialization.json.put
import kotlinx.serialization.json.putJsonObject

/**
 * A single parameter of an [AgentToolDescriptor], carrying enough info to emit a JSON-schema
 * property and to describe whether the model must supply it. [jsonType] is one of
 * `string | integer | number | boolean | array`; [itemType] is set only for `array`.
 */
data class AgentToolParamSpec(
    val name: String,
    val jsonType: String,
    val description: String,
    val required: Boolean,
    val itemType: String? = null,
)

/**
 * A built-in WeAgent tool, generated by the `@AgentTool` KSP scanner. [invoker] unpacks a
 * validated [AgentToolArgs] and calls the underlying function, returning a model-readable string.
 */
data class AgentToolDescriptor(
    val name: String,
    val description: String,
    val sideEffect: Boolean,
    val group: String,
    val params: List<AgentToolParamSpec>,
    val invoker: suspend (AgentToolArgs) -> String,
) {
    /** Builds the JSON-schema object (`{type:object, properties, required}`) for this tool. */
    fun buildJsonSchema(): JsonObject = buildJsonObject {
        put("type", "object")
        putJsonObject("properties") {
            params.forEach { p ->
                putJsonObject(p.name) {
                    put("type", p.jsonType)
                    put("description", p.description)
                    if (p.jsonType == "array") {
                        putJsonObject("items") { put("type", p.itemType ?: "string") }
                    }
                }
            }
        }
        put("required", JsonArray(params.filter { it.required }.map { JsonPrimitive(it.name) }))
    }
}

/**
 * Typed, forgiving accessor over a tool call's JSON argument object. Non-null accessors throw
 * [AgentToolArgException] when a required argument is missing or the wrong shape; the message is
 * surfaced back to the model as the tool result so it can self-correct.
 */
class AgentToolArgs(private val obj: JsonObject) {

    class AgentToolArgException(message: String) : RuntimeException(message)

    private fun raw(name: String) = obj[name]

    fun stringOrNull(name: String): String? =
        (raw(name) as? JsonPrimitive)?.let { if (it.isString || it.content != "null") it.content else null }

    fun string(name: String): String =
        stringOrNull(name) ?: throw AgentToolArgException("Missing required string argument '$name'")

    fun intOrNull(name: String): Int? = (raw(name) as? JsonPrimitive)?.intOrNull
    fun int(name: String): Int =
        intOrNull(name) ?: throw AgentToolArgException("Missing/invalid required integer argument '$name'")

    fun longOrNull(name: String): Long? = (raw(name) as? JsonPrimitive)?.longOrNull
    fun long(name: String): Long =
        longOrNull(name) ?: throw AgentToolArgException("Missing/invalid required integer argument '$name'")

    fun doubleOrNull(name: String): Double? = (raw(name) as? JsonPrimitive)?.doubleOrNull
    fun double(name: String): Double =
        doubleOrNull(name) ?: throw AgentToolArgException("Missing/invalid required number argument '$name'")

    fun boolOrNull(name: String): Boolean? = (raw(name) as? JsonPrimitive)?.booleanOrNull
    fun bool(name: String): Boolean =
        boolOrNull(name) ?: throw AgentToolArgException("Missing/invalid required boolean argument '$name'")

    fun stringListOrNull(name: String): List<String>? =
        (raw(name) as? JsonArray)?.map { it.jsonPrimitive.content }

    fun stringList(name: String): List<String> =
        stringListOrNull(name) ?: throw AgentToolArgException("Missing required array argument '$name'")
}
